import { storage } from "./storage";

const seedRestaurants = [
  {
    name: "명동교자",
    nameEn: "Myeongdong Kyoja",
    category: "한식",
    cuisine: "만두, 칼국수",
    district: "명동",
    address: "서울 중구 명동10길 29",
    description: "1966년부터 이어온 전통 칼국수 맛집. 손으로 빚은 만두와 얼큰한 칼국수가 유명합니다.",
    descriptionEn: "Traditional kalguksu (knife-cut noodles) restaurant since 1966. Famous for handmade dumplings and spicy noodle soup.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
    openHours: "10:30-21:30 (연중무휴)",
    phone: "02-776-5348",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "광장시장",
    nameEn: "Gwangjang Market",
    category: "전통시장",
    cuisine: "빈대떡, 마약김밥, 육회",
    district: "종로",
    address: "서울 종로구 창경궁로 88",
    description: "100년 역사의 서울 대표 전통시장. 빈대떡, 마약김밥, 육회 등 다양한 길거리 음식을 즐길 수 있습니다.",
    descriptionEn: "Historic 100-year-old traditional market in Seoul. Famous for bindaetteok (mung bean pancakes), mayak gimbap, and yukhoe (Korean beef tartare).",
    priceRange: 1,
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800",
    openHours: "09:00-23:00",
    phone: "02-2267-0291",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "토속촌삼계탕",
    nameEn: "Tosokchon Samgyetang",
    category: "한식",
    cuisine: "삼계탕",
    district: "경복궁",
    address: "서울 종로구 자하문로5길 5",
    description: "경복궁 근처 40년 전통의 삼계탕 전문점. 국내산 영계와 한약재로 만든 보양식입니다.",
    descriptionEn: "40-year-old ginseng chicken soup restaurant near Gyeongbokgung Palace. Made with Korean young chicken and traditional medicinal herbs.",
    priceRange: 3,
    imageUrl: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
    openHours: "10:00-22:00",
    phone: "02-737-7444",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "우래옥",
    nameEn: "Wooraeok",
    category: "한식",
    cuisine: "평양냉면",
    district: "을지로",
    address: "서울 중구 창경궁로 62-29",
    description: "1946년 개업한 서울 3대 평양냉면 맛집. 깊은 육수와 쫄깃한 면발이 일품입니다.",
    descriptionEn: "Established in 1946, one of Seoul's top 3 Pyongyang-style cold noodle restaurants. Known for rich broth and chewy noodles.",
    priceRange: 3,
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
    openHours: "11:30-21:00 (월요일 휴무)",
    phone: "02-2265-0151",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "미진",
    nameEn: "Mijin",
    category: "한식",
    cuisine: "육회비빔밥",
    district: "압구정",
    address: "서울 강남구 압구정로2길 27",
    description: "신선한 육회와 비빔밥으로 유명한 맛집. 1960년대부터 3대째 이어온 전통의 맛입니다.",
    descriptionEn: "Famous for fresh yukhoe (beef tartare) bibimbap. Third generation family restaurant since the 1960s.",
    priceRange: 3,
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800",
    openHours: "11:30-22:00",
    phone: "02-548-3200",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "이문설농탕",
    nameEn: "Imun Seolleongtang",
    category: "한식",
    cuisine: "설렁탕",
    district: "이문동",
    address: "서울 동대문구 이문로 34",
    description: "1907년 개업한 100년 전통 설렁탕 맛집. 진한 국물과 부드러운 고기가 일품입니다.",
    descriptionEn: "Established in 1907, a century-old seolleongtang (ox bone soup) restaurant. Famous for rich broth and tender meat.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1618329482768-8e3ea6ce8b60?w=800",
    openHours: "00:00-24:00 (24시간)",
    phone: "02-969-1010",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "한일관",
    nameEn: "Hanilkwan",
    category: "한식",
    cuisine: "갈비구이, 한정식",
    district: "청담",
    address: "서울 강남구 압구정로2길 35",
    description: "1939년 개업한 고급 한정식 전문점. 특제 갈비구이와 다양한 반찬이 유명합니다.",
    descriptionEn: "Upscale Korean restaurant established in 1939. Famous for special galbi (grilled ribs) and various banchan (side dishes).",
    priceRange: 4,
    imageUrl: "https://images.unsplash.com/photo-1588207036722-0a86fe9f2b03?w=800",
    openHours: "11:30-22:00",
    phone: "02-547-9081",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "하동관",
    nameEn: "Hadongkwan",
    category: "한식",
    cuisine: "곰탕",
    district: "명동",
    address: "서울 중구 명동9길 12",
    description: "1939년부터 3대째 이어온 곰탕 전문점. 깊고 진한 곰탕 국물이 일품입니다.",
    descriptionEn: "Third-generation gomtang (beef bone soup) restaurant since 1939. Known for deep and rich broth.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800",
    openHours: "07:00-21:30 (일요일 휴무)",
    phone: "02-776-5656",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "진미평양냉면",
    nameEn: "Jinmi Pyongyang Naengmyeon",
    category: "한식",
    cuisine: "평양냉면",
    district: "종로",
    address: "서울 종로구 돈화문로11가길 34",
    description: "1953년 개업한 평양냉면 전문점. 담백한 육수와 쫄깃한 면발이 특징입니다.",
    descriptionEn: "Pyongyang-style cold noodle restaurant since 1953. Characterized by light broth and chewy noodles.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
    openHours: "11:00-21:00",
    phone: "02-733-6566",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "발우공양",
    nameEn: "Balwoo Gongyang",
    category: "사찰음식",
    cuisine: "사찰음식, 비건",
    district: "종로",
    address: "서울 종로구 우정국로 56",
    description: "미슐랭 1스타 사찰음식 레스토랑. 정갈한 비건 한정식을 맛볼 수 있습니다.",
    descriptionEn: "Michelin 1-star temple food restaurant. Offers refined vegan Korean cuisine.",
    priceRange: 4,
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    openHours: "12:00-15:00, 18:00-21:00 (일요일 휴무)",
    phone: "02-2031-2081",
    isVegan: 1,
    isHalal: 1,
  },
  {
    name: "삼원가든",
    nameEn: "Samwon Garden",
    category: "한식",
    cuisine: "한우구이",
    district: "압구정",
    address: "서울 강남구 압구정로45길 16",
    description: "1976년 개업한 고급 한우 전문점. 넓은 정원과 함께 최고급 한우를 즐길 수 있습니다.",
    descriptionEn: "Premium Korean beef restaurant since 1976. Enjoy top-quality hanwoo in a beautiful garden setting.",
    priceRange: 4,
    imageUrl: "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800",
    openHours: "11:30-22:00",
    phone: "02-548-3030",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "북촌손만두",
    nameEn: "Bukchon Son Mandu",
    category: "한식",
    cuisine: "만두, 만둣국",
    district: "북촌",
    address: "서울 종로구 북촌로 5길 27",
    description: "북촌 한옥마을의 손만두 전문점. 매일 아침 직접 빚은 만두가 일품입니다.",
    descriptionEn: "Handmade dumpling restaurant in Bukchon Hanok Village. Fresh dumplings made every morning.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800",
    openHours: "10:30-21:00",
    phone: "02-742-1970",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "전주중앙회관",
    nameEn: "Jeonju Jungang Hoegwan",
    category: "한식",
    cuisine: "비빔밥, 콩나물국밥",
    district: "명동",
    address: "서울 중구 삼일대로 299",
    description: "1954년 개업한 전주 비빔밥 원조집. 고소한 참기름과 신선한 나물이 어우러진 비빔밥입니다.",
    descriptionEn: "Original Jeonju bibimbap restaurant since 1954. Features aromatic sesame oil and fresh vegetables.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=800",
    openHours: "11:30-21:30",
    phone: "02-776-3525",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "진진",
    nameEn: "Jin Jin",
    category: "한식",
    cuisine: "바라",
    district: "종로",
    address: "서울 종로구 자하문로 149",
    description: "미슐랭 가이드 선정 현대적 한식 레스토랑. 전통 한식을 모던하게 재해석합니다.",
    descriptionEn: "Michelin Guide selected modern Korean restaurant. Reinterprets traditional Korean cuisine with a contemporary twist.",
    priceRange: 4,
    imageUrl: "https://images.unsplash.com/photo-1580822184713-fc5400e7fe10?w=800",
    openHours: "12:00-15:00, 18:00-22:00 (월요일 휴무)",
    phone: "02-730-1079",
    isVegan: 0,
    isHalal: 0,
  },
  {
    name: "오장동흥남집",
    nameEn: "Ojang-dong Heungnamjip",
    category: "한식",
    cuisine: "냉면, 족발",
    district: "마포",
    address: "서울 마포구 토정로 35",
    description: "1987년 개업한 함흥냉면과 족발 전문점. 매콤달콤한 함흥냉면이 인기입니다.",
    descriptionEn: "Hamheung-style cold noodles and jokbal restaurant since 1987. Famous for sweet and spicy cold noodles.",
    priceRange: 2,
    imageUrl: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800",
    openHours: "11:00-23:00",
    phone: "02-704-4399",
    isVegan: 0,
    isHalal: 0,
  },
];

async function seed() {
  console.log("🌱 Seeding restaurants...");
  
  for (const restaurant of seedRestaurants) {
    try {
      await storage.createRestaurant(restaurant);
      console.log(`✅ Added: ${restaurant.name}`);
    } catch (error) {
      console.error(`❌ Failed to add ${restaurant.name}:`, error);
    }
  }
  
  console.log("✨ Seeding complete!");
  process.exit(0);
}

seed();
