import { drizzle as drizzlePostgres } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { restaurants, menus, restaurantInsights } from "../shared/schema";

const DATABASE_URL = process.env.DATABASE_URL!;
const client = postgres(DATABASE_URL, {
  max: 10,
  idle_timeout: 20,
  connect_timeout: 10,
});
const db = drizzlePostgres(client);

const SEOUL_RESTAURANTS = [
  {
    name: "미진",
    nameEn: "Mijin",
    category: "한식",
    cuisine: "육류",
    district: "강남구",
    address: "서울 강남구 논현동 132-3",
    latitude: 37.5118,
    longitude: 127.0268,
    description: "1962년부터 이어온 전통 육류 전문점. 한우 육회와 불고기로 유명하며, 정갈한 한식 밑반찬이 일품입니다.",
    descriptionEn: "Traditional Korean beef restaurant since 1962. Famous for Korean beef tartare and bulgogi with refined side dishes.",
    priceRange: 3,
    imageUrl: "/images/restaurants/mijin.jpg",
    openHours: "11:00-22:00",
    phone: "02-542-3659",
    city: "서울",
    districtDetail: "논현동",
  },
  {
    name: "광장시장 마약김밥",
    nameEn: "Gwangjang Market Gimbap",
    category: "한식",
    cuisine: "분식",
    district: "종로구",
    address: "서울 종로구 창경궁로 88 광장시장",
    latitude: 37.5705,
    longitude: 126.9997,
    description: "광장시장의 명물 마약김밥. 중독성 있는 맛으로 유명하며 저렴한 가격에 푸짐한 양을 자랑합니다.",
    descriptionEn: "Famous 'addictive' gimbap at Gwangjang Market. Known for its large portions at affordable prices.",
    priceRange: 1,
    imageUrl: "/images/restaurants/mayak-gimbap.jpg",
    openHours: "09:00-22:00",
    phone: "010-1234-5678",
    city: "서울",
    districtDetail: "창경궁로",
  },
  {
    name: "진미평양냉면",
    nameEn: "Jinmi Pyongyang Naengmyeon",
    category: "한식",
    cuisine: "냉면",
    district: "중구",
    address: "서울 중구 을지로 동 충무로1가 24-11",
    latitude: 37.5617,
    longitude: 126.9958,
    description: "평양식 냉면의 정통을 지키는 노포. 깊은 육수와 쫄깃한 면발이 특징입니다.",
    descriptionEn: "Traditional Pyongyang-style cold noodles. Known for rich broth and chewy noodles.",
    priceRange: 2,
    imageUrl: "/images/restaurants/jinmi-naengmyeon.jpg",
    openHours: "11:30-21:00",
    phone: "02-2266-6719",
    city: "서울",
    districtDetail: "충무로1가",
  },
  {
    name: "삼원가든",
    nameEn: "Samwon Garden",
    category: "한식",
    cuisine: "육류",
    district: "강남구",
    address: "서울 강남구 신사동 642-9",
    latitude: 37.5239,
    longitude: 127.0207,
    description: "강남의 대표 한우 전문점. 넓은 정원과 함께 즐기는 프리미엄 한우 갈비가 유명합니다.",
    descriptionEn: "Premium Korean beef restaurant in Gangnam. Famous for galbi (ribs) in a spacious garden setting.",
    priceRange: 4,
    imageUrl: "/images/restaurants/samwon-garden.jpg",
    openHours: "11:30-22:00",
    phone: "02-548-3030",
    city: "서울",
    districtDetail: "신사동",
  },
  {
    name: "토속촌",
    nameEn: "Tosokchon",
    category: "한식",
    cuisine: "탕/국",
    district: "종로구",
    address: "서울 종로구 체부동 85-1",
    latitude: 37.5835,
    longitude: 126.9734,
    description: "경복궁 근처의 유명 삼계탕 전문점. 진한 국물과 부드러운 닭고기로 관광객들에게 인기입니다.",
    descriptionEn: "Famous ginseng chicken soup restaurant near Gyeongbokgung Palace. Popular among tourists.",
    priceRange: 3,
    imageUrl: "/images/restaurants/tosokchon.jpg",
    openHours: "10:00-22:00",
    phone: "02-737-7444",
    city: "서울",
    districtDetail: "체부동",
  },
  {
    name: "명동교자",
    nameEn: "Myeongdong Kyoja",
    category: "한식",
    cuisine: "만두/칼국수",
    district: "중구",
    address: "서울 중구 명동2가 25-2",
    latitude: 37.5636,
    longitude: 126.9843,
    description: "명동의 대표 칼국수 맛집. 손칼국수와 김치만두가 시그니처 메뉴입니다.",
    descriptionEn: "Famous hand-cut noodle soup in Myeongdong. Signature dishes include kalguksu and kimchi dumplings.",
    priceRange: 2,
    imageUrl: "/images/restaurants/myeongdong-kyoja.jpg",
    openHours: "10:30-21:30",
    phone: "02-776-5348",
    city: "서울",
    districtDetail: "명동2가",
  },
  {
    name: "이태원 술탄케밥",
    nameEn: "Itaewon Sultan Kebab",
    category: "한식",
    cuisine: "이슬람 음식",
    district: "용산구",
    address: "서울 용산구 이태원동 119-25",
    latitude: 37.5345,
    longitude: 126.9945,
    description: "이태원의 할랄 케밥 전문점. 정통 터키식 케밥과 샤워마를 제공합니다.",
    descriptionEn: "Halal kebab restaurant in Itaewon. Serves authentic Turkish kebabs and shawarma.",
    priceRange: 2,
    isHalal: 1,
    imageUrl: "/images/restaurants/sultan-kebab.jpg",
    openHours: "11:00-23:00",
    phone: "02-796-7582",
    city: "서울",
    districtDetail: "이태원동",
  },
  {
    name: "식물",
    nameEn: "Plant",
    category: "한식",
    cuisine: "비건",
    district: "마포구",
    address: "서울 마포구 서교동 395-14",
    latitude: 37.5557,
    longitude: 126.9223,
    description: "홍대 인근의 비건 한식 레스토랑. 전통 한식을 식물성 재료로 재해석한 메뉴들이 인기입니다.",
    descriptionEn: "Vegan Korean restaurant near Hongdae. Reinterprets traditional Korean dishes with plant-based ingredients.",
    priceRange: 3,
    isVegan: 1,
    imageUrl: "/images/restaurants/plant.jpg",
    openHours: "12:00-21:00",
    phone: "02-332-5884",
    city: "서울",
    districtDetail: "서교동",
  },
  {
    name: "진옥화 할매 원조 닭한마리",
    nameEn: "Jin Ok-hwa Original Chicken",
    category: "한식",
    cuisine: "탕/국",
    district: "종로구",
    address: "서울 종로구 종로5가 265-22",
    latitude: 37.5719,
    longitude: 127.0043,
    description: "동대문 닭한마리 골목의 원조. 푸짐한 닭고기와 칼국수 사리가 일품입니다.",
    descriptionEn: "Original whole chicken soup in Dongdaemun. Famous for generous portions with noodles.",
    priceRange: 2,
    imageUrl: "/images/restaurants/chicken-hanmari.jpg",
    openHours: "10:30-01:00",
    phone: "02-2279-9979",
    city: "서울",
    districtDetail: "종로5가",
  },
  {
    name: "우래옥",
    nameEn: "Woo Lae Oak",
    category: "한식",
    cuisine: "냉면",
    district: "중구",
    address: "서울 중구 을지로4가 118-1",
    latitude: 37.5662,
    longitude: 126.9975,
    description: "1946년부터 이어온 평양냉면 명가. 4대째 이어지는 전통 육수 비법이 유명합니다.",
    descriptionEn: "Historic Pyongyang cold noodles since 1946. Fourth-generation family recipe for broth.",
    priceRange: 3,
    imageUrl: "/images/restaurants/woo-lae-oak.jpg",
    openHours: "11:30-21:30",
    phone: "02-2265-0151",
    city: "서울",
    districtDetail: "을지로4가",
  },
  {
    name: "한식진미 궁",
    nameEn: "Korean Fine Dining Gung",
    category: "한식",
    cuisine: "한정식",
    district: "강남구",
    address: "서울 강남구 청담동 91-4",
    latitude: 37.5237,
    longitude: 127.0476,
    description: "청담동의 프리미엄 한정식 레스토랑. 계절 식재료를 활용한 코스 요리를 제공합니다.",
    descriptionEn: "Premium Korean course meal restaurant in Cheongdam. Features seasonal ingredients.",
    priceRange: 4,
    imageUrl: "/images/restaurants/gung.jpg",
    openHours: "12:00-22:00",
    phone: "02-547-5580",
    city: "서울",
    districtDetail: "청담동",
  },
  {
    name: "북촌손만두",
    nameEn: "Bukchon Son Mandu",
    category: "한식",
    cuisine: "만두/칼국수",
    district: "종로구",
    address: "서울 종로구 삼청동 35-169",
    latitude: 37.5820,
    longitude: 126.9824,
    description: "북촌 한옥마을의 손만두 전문점. 매일 아침 직접 빚는 만두가 자랑입니다.",
    descriptionEn: "Handmade dumpling restaurant in Bukchon Hanok Village. Fresh dumplings made daily.",
    priceRange: 2,
    imageUrl: "/images/restaurants/bukchon-mandu.jpg",
    openHours: "11:00-21:00",
    phone: "02-742-7050",
    city: "서울",
    districtDetail: "삼청동",
  },
  {
    name: "을밀대",
    nameEn: "Eulmildae",
    category: "한식",
    cuisine: "냉면",
    district: "중구",
    address: "서울 중구 을지로3가 276-1",
    latitude: 37.5662,
    longitude: 126.9915,
    description: "을지로의 대표 함흥냉면 맛집. 회냉면과 비빔냉면이 시그니처 메뉴입니다.",
    descriptionEn: "Famous Hamheung-style cold noodles in Euljiro. Signature dishes include bibim naengmyeon.",
    priceRange: 2,
    imageUrl: "/images/restaurants/eulmildae.jpg",
    openHours: "11:00-21:00",
    phone: "02-2263-0876",
    city: "서울",
    districtDetail: "을지로3가",
  },
  {
    name: "곤드레",
    nameEn: "Gondeure",
    category: "한식",
    cuisine: "밥/비빔밥",
    district: "마포구",
    address: "서울 마포구 합정동 366-6",
    latitude: 37.5494,
    longitude: 126.9125,
    description: "합정동의 곤드레밥 전문점. 강원도 산나물로 만든 건강한 한식입니다.",
    descriptionEn: "Gondeure rice specialty in Hapjeong. Healthy Korean meal with mountain herbs from Gangwon-do.",
    priceRange: 2,
    imageUrl: "/images/restaurants/gondeure.jpg",
    openHours: "11:30-21:30",
    phone: "02-334-0020",
    city: "서울",
    districtDetail: "합정동",
  },
  {
    name: "육전식당",
    nameEn: "Yukjeon Sikdang",
    category: "한식",
    cuisine: "육류",
    district: "용산구",
    address: "서울 용산구 한남동 683-142",
    latitude: 37.5347,
    longitude: 127.0021,
    description: "한남동의 육전(고기전) 전문점. 한우로 만든 육전과 된장찌개가 일품입니다.",
    descriptionEn: "Korean beef pancake specialty in Hannam. Famous for yukjeon and doenjang jjigae.",
    priceRange: 3,
    imageUrl: "/images/restaurants/yukjeon.jpg",
    openHours: "11:00-22:00",
    phone: "02-797-3735",
    city: "서울",
    districtDetail: "한남동",
  },
  {
    name: "종로 김밥",
    nameEn: "Jongno Gimbap",
    category: "한식",
    cuisine: "분식",
    district: "종로구",
    address: "서울 종로구 종로2가 8-3",
    latitude: 37.5714,
    longitude: 126.9826,
    description: "종로의 24시간 김밥 맛집. 저렴한 가격에 다양한 김밥과 분식을 즐길 수 있습니다.",
    descriptionEn: "24-hour gimbap restaurant in Jongno. Affordable variety of gimbap and snacks.",
    priceRange: 1,
    imageUrl: "/images/restaurants/jongno-gimbap.jpg",
    openHours: "24시간",
    phone: "02-733-4848",
    city: "서울",
    districtDetail: "종로2가",
  },
  {
    name: "신선설렁탕",
    nameEn: "Shinsun Seolleongtang",
    category: "한식",
    cuisine: "탕/국",
    district: "관악구",
    address: "서울 관악구 봉천동 1688-27",
    latitude: 37.4813,
    longitude: 126.9516,
    description: "사당동의 설렁탕 맛집. 24시간 운영하며 진한 사골 육수가 특징입니다.",
    descriptionEn: "Seolleongtang (ox bone soup) restaurant in Sadang. Open 24 hours with rich beef broth.",
    priceRange: 2,
    imageUrl: "/images/restaurants/shinsun-seolleongtang.jpg",
    openHours: "24시간",
    phone: "02-876-3456",
    city: "서울",
    districtDetail: "봉천동",
  },
  {
    name: "대성집",
    nameEn: "Daesung House",
    category: "한식",
    cuisine: "육류",
    district: "마포구",
    address: "서울 마포구 마포동 353-12",
    latitude: 37.5425,
    longitude: 126.9459,
    description: "마포의 오래된 곱창 전문점. 신선한 곱창과 양이 자랑입니다.",
    descriptionEn: "Historic gopchang (intestine) restaurant in Mapo. Known for fresh offal.",
    priceRange: 3,
    imageUrl: "/images/restaurants/daesung.jpg",
    openHours: "16:00-03:00",
    phone: "02-719-1545",
    city: "서울",
    districtDetail: "마포동",
  },
  {
    name: "오징어집",
    nameEn: "Ojingeo House",
    category: "한식",
    cuisine: "해산물",
    district: "강남구",
    address: "서울 강남구 역삼동 825-23",
    latitude: 37.5007,
    longitude: 127.0366,
    description: "강남의 오징어 요리 전문점. 오징어 볶음과 오징어 회가 인기입니다.",
    descriptionEn: "Squid specialty restaurant in Gangnam. Famous for stir-fried squid and raw squid.",
    priceRange: 3,
    imageUrl: "/images/restaurants/ojingeo.jpg",
    openHours: "17:00-01:00",
    phone: "02-567-5433",
    city: "서울",
    districtDetail: "역삼동",
  },
  {
    name: "청진옥",
    nameEn: "Cheongjin Ok",
    category: "한식",
    cuisine: "해장국",
    district: "종로구",
    address: "서울 종로구 청진동 125",
    latitude: 37.5706,
    longitude: 126.9795,
    description: "종로의 유명 해장국집. 선지해장국과 우거지해장국이 대표 메뉴입니다.",
    descriptionEn: "Famous hangover soup restaurant in Jongno. Specializes in blood sausage soup.",
    priceRange: 2,
    imageUrl: "/images/restaurants/cheongjin-ok.jpg",
    openHours: "24시간",
    phone: "02-735-1690",
    city: "서울",
    districtDetail: "청진동",
  },
  {
    name: "한우마을",
    nameEn: "Hanwoo Village",
    category: "한식",
    cuisine: "육류",
    district: "송파구",
    address: "서울 송파구 잠실동 202-1",
    latitude: 37.5133,
    longitude: 127.0829,
    description: "잠실의 한우 전문점. 1++등급 한우와 다양한 부위를 즐길 수 있습니다.",
    descriptionEn: "Premium Korean beef restaurant in Jamsil. Serves grade 1++ hanwoo with various cuts.",
    priceRange: 4,
    imageUrl: "/images/restaurants/hanwoo-village.jpg",
    openHours: "11:30-22:00",
    phone: "02-415-8585",
    city: "서울",
    districtDetail: "잠실동",
  },
  {
    name: "낙지 한마당",
    nameEn: "Nakji Hanmadang",
    category: "한식",
    cuisine: "해산물",
    district: "마포구",
    address: "서울 마포구 신촌동 134-96",
    latitude: 37.5563,
    longitude: 126.9363,
    description: "신촌의 낙지 요리 전문점. 낙지볶음과 연포탕이 시그니처 메뉴입니다.",
    descriptionEn: "Octopus specialty in Sinchon. Famous for spicy stir-fried octopus and yeonpotang.",
    priceRange: 2,
    imageUrl: "/images/restaurants/nakji.jpg",
    openHours: "11:00-23:00",
    phone: "02-393-4040",
    city: "서울",
    districtDetail: "신촌동",
  },
  {
    name: "전주식당",
    nameEn: "Jeonju Sikdang",
    category: "한식",
    cuisine: "밥/비빔밥",
    district: "강남구",
    address: "서울 강남구 신사동 549-8",
    latitude: 37.5217,
    longitude: 127.0203,
    description: "신사동의 전주 비빔밥 전문점. 풍부한 나물과 육회가 토핑된 비빔밥이 유명합니다.",
    descriptionEn: "Jeonju bibimbap specialty in Sinsa. Famous for bibimbap topped with abundant vegetables and beef.",
    priceRange: 3,
    imageUrl: "/images/restaurants/jeonju-bibimbap.jpg",
    openHours: "11:00-21:00",
    phone: "02-544-3220",
    city: "서울",
    districtDetail: "신사동",
  },
  {
    name: "산촌",
    nameEn: "Sanchon",
    category: "한식",
    cuisine: "사찰음식",
    district: "종로구",
    address: "서울 종로구 인사동 30-13",
    latitude: 37.5739,
    longitude: 126.9854,
    description: "인사동의 사찰 음식 전문점. 채식 위주의 건강한 한식 코스를 제공합니다.",
    descriptionEn: "Temple food restaurant in Insadong. Offers healthy vegetarian Korean course meals.",
    priceRange: 3,
    isVegan: 1,
    imageUrl: "/images/restaurants/sanchon.jpg",
    openHours: "12:00-21:00",
    phone: "02-735-0312",
    city: "서울",
    districtDetail: "인사동",
  },
  {
    name: "대포집",
    nameEn: "Daepojip",
    category: "한식",
    cuisine: "해산물",
    district: "마포구",
    address: "서울 마포구 동교동 156-17",
    latitude: 37.5583,
    longitude: 126.9254,
    description: "홍대 앞의 대폿집 스타일 주점. 신선한 해산물 안주와 막걸리가 인기입니다.",
    descriptionEn: "Daepojip-style tavern near Hongdae. Popular for fresh seafood and makgeolli.",
    priceRange: 2,
    imageUrl: "/images/restaurants/daepojip.jpg",
    openHours: "17:00-02:00",
    phone: "02-325-8899",
    city: "서울",
    districtDetail: "동교동",
  },
  {
    name: "제주집",
    nameEn: "Jeju House",
    category: "한식",
    cuisine: "고기국수",
    district: "용산구",
    address: "서울 용산구 이태원동 123-45",
    latitude: 37.5342,
    longitude: 126.9938,
    description: "이태원의 제주 음식 전문점. 고기국수와 흑돼지 구이가 대표 메뉴입니다.",
    descriptionEn: "Jeju cuisine restaurant in Itaewon. Specializes in pork noodle soup and black pork BBQ.",
    priceRange: 3,
    imageUrl: "/images/restaurants/jeju-house.jpg",
    openHours: "11:00-22:00",
    phone: "02-796-8822",
    city: "서울",
    districtDetail: "이태원동",
  },
  {
    name: "백년옥",
    nameEn: "Baeknyeon Ok",
    category: "한식",
    cuisine: "설렁탕/곰탕",
    district: "중구",
    address: "서울 중구 남대문로5가 436",
    latitude: 37.5598,
    longitude: 126.9768,
    description: "남대문 시장 근처의 설렁탕 전문점. 100년 전통의 맛을 자랑합니다.",
    descriptionEn: "Historic seolleongtang restaurant near Namdaemun Market. 100 years of tradition.",
    priceRange: 2,
    imageUrl: "/images/restaurants/baeknyeon-ok.jpg",
    openHours: "24시간",
    phone: "02-776-4650",
    city: "서울",
    districtDetail: "남대문로5가",
  },
  {
    name: "진주회관",
    nameEn: "Jinju Hoegwan",
    category: "한식",
    cuisine: "밥/비빔밥",
    district: "강남구",
    address: "서울 강남구 역삼동 647-15",
    latitude: 37.5003,
    longitude: 127.0327,
    description: "강남의 진주 비빔밥 전문점. 육회 비빔밥과 돌솥 비빔밥이 인기입니다.",
    descriptionEn: "Jinju bibimbap specialty in Gangnam. Famous for beef tartare bibimbap and stone pot bibimbap.",
    priceRange: 3,
    imageUrl: "/images/restaurants/jinju-hoegwan.jpg",
    openHours: "11:00-22:00",
    phone: "02-567-3726",
    city: "서울",
    districtDetail: "역삼동",
  },
  {
    name: "장수촌",
    nameEn: "Jangsu Chon",
    category: "한식",
    cuisine: "탕/국",
    district: "송파구",
    address: "서울 송파구 가락동 79-7",
    latitude: 37.4926,
    longitude: 127.1198,
    description: "가락시장 근처의 곰탕 전문점. 진한 사골 곰탕과 도가니탕이 유명합니다.",
    descriptionEn: "Gomtang (beef bone soup) restaurant near Garak Market. Famous for rich ox bone soup.",
    priceRange: 2,
    imageUrl: "/images/restaurants/jangsu-chon.jpg",
    openHours: "24시간",
    phone: "02-443-0260",
    city: "서울",
    districtDetail: "가락동",
  },
  {
    name: "청기와집",
    nameEn: "Cheonggiwajip",
    category: "한식",
    cuisine: "육류",
    district: "종로구",
    address: "서울 종로구 세종로 1-80",
    latitude: 37.5726,
    longitude: 126.9769,
    description: "광화문 근처의 돼지갈비 전문점. 양념 돼지갈비와 된장찌개가 일품입니다.",
    descriptionEn: "Pork galbi restaurant near Gwanghwamun. Famous for marinated pork ribs and doenjang jjigae.",
    priceRange: 3,
    imageUrl: "/images/restaurants/cheonggiwajip.jpg",
    openHours: "11:00-22:00",
    phone: "02-735-7171",
    city: "서울",
    districtDetail: "세종로",
  },
];

async function seedRestaurants() {
  console.log("Starting restaurant seed...");
  
  try {
    for (const restaurant of SEOUL_RESTAURANTS) {
      await db.insert(restaurants).values(restaurant);
      console.log(`✓ Inserted: ${restaurant.name}`);
    }
    
    console.log(`\n✅ Successfully seeded ${SEOUL_RESTAURANTS.length} restaurants!`);
  } catch (error) {
    console.error("❌ Error seeding restaurants:", error);
    throw error;
  } finally {
    await client.end();
  }
}

seedRestaurants();
